beyondtheadmin/clients/urls.py
from django.urls import path

from .views.dashboard import ClientAppView, ClientDeleteView, ClientListView


app_name = "clients"
urlpatterns = [
    path("new", view=ClientAppView.as_view(), name="create"),
    path("<uuid:pk>/edit", view=ClientAppView.as_view(), name="update"),
    path("<uuid:pk>/delete", view=ClientDeleteView.as_view(), name="delete"),
    path("", view=ClientListView.as_view(), name="list"),
]

beyondtheadmin/invoices/urls.py
from django.urls import path

from .views import dashboard as views


app_name = "invoices"
urlpatterns = [
    path("new/", view=views.InvoiceCreateView.as_view(), name="create"),
    path("<uuid:pk>/cancel", view=views.InvoiceCancelView.as_view(), name="cancel"),
    path(
        "<uuid:pk>/duplicate",
        view=views.InvoiceDuplicateView.as_view(),
        name="duplicate",
    ),
    path(
        "<uuid:pk>/send-reminder",
        view=views.InvoiceSendReminderEmailView.as_view(),
        name="reminder",
    ),
    path("<uuid:pk>/send", view=views.InvoiceSendMailView.as_view(), name="send"),
    path(
        "<uuid:pk>/mark-as-paid",
        view=views.InvoiceMarkPaidView.as_view(),
        name="mark_paid",
    ),
    path(
        "<uuid:pk>/mark-as-sent",
        view=views.InvoiceSnailMailUpdateView.as_view(),
        name="mark_sent",
    ),
    path("<uuid:pk>/update", view=views.InvoiceUpdateView.as_view(), name="update"),
    path("", view=views.InvoiceListView.as_view(), name="list"),
]

beyondtheadmin/users/urls.py
from django.urls import path

from beyondtheadmin.users.views import user_detail_view, user_redirect_view, user_update_view


app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

from rest_framework.authtoken.views import obtain_auth_token

from beyondtheadmin.dashboard.views import dashboard
from beyondtheadmin.invoices.views.public import InvoiceDetailView, qrbill


admin.autodiscover()
admin.site.enable_nav_sidebar = False

urlpatterns = i18n_patterns(
    path("", dashboard, name="dashboard"),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("clients/", include("beyondtheadmin.clients.urls", namespace="clients")),
    path("companies/", include("beyondtheadmin.companies.urls", namespace="companies")),
    path("invoices/", include("beyondtheadmin.invoices.urls", namespace="invoices")),
    path("users/", include("beyondtheadmin.users.urls", namespace="users")),
    prefix_default_language=False,
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    # Why is it here? invoices are translated to the client's language. We don't want to find ourselves
    # under a case where one could change the language. Therefore it has to find place here.
    path("invoice/<uuid:pk>/", view=InvoiceDetailView.as_view(), name="invoice-print"),
    path("invoice/<uuid:pk>/qrbill.svg", view=qrbill, name="qrbill"),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

beyondtheadmin/utils/models.py
import uuid

from django.db import models

from model_utils.models import TimeStampedModel


class UUIDModel(TimeStampedModel):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

beyondtheadmin/api/views.py
from django.http import JsonResponse


def csrf_token(request):
    return JsonResponse({"csrf_token": request.COOKIES.get("csrftoken")})

beyondtheadmin/clients/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from .forms import ClientForm
from .models import Client


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy("clients:list")
    template_name = "clients/create.html"

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    success_url = reverse_lazy("clients:list")
    template_name = "clients/confirm_delete.html"

    def get_queryset(self):
        return Client.objects.filter(company__users=self.request.user)


class ClientListView(LoginRequiredMixin, ListView):
    model = Client
    template_name = "clients/list.html"

    def get_queryset(self):
        return Client.objects.filter(company__users=self.request.user)


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy("clients:list")
    template_name = "clients/update.html"

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def get_queryset(self):
        return Client.objects.filter(company__users=self.request.user)

beyondtheadmin/clients/views/api.py
from rest_framework import viewsets
from rest_framework.authentication import SessionAuthentication

from beyondtheadmin.api.permissions import IsCompanyOwnedByUser

from ..models import Client
from ..serializers import ClientListSerializer, ClientSerializer


class ClientViewSet(viewsets.ModelViewSet):
    queryset = Client.objects.all()
    serializer_class = ClientSerializer
    permission_classes = [IsCompanyOwnedByUser]
    authentication_classes = [SessionAuthentication]

    def get_queryset(self):
        queryset = super().get_queryset().filter(company__users=self.request.user)
        if "company_uuid" in self.request.query_params:
            company_uuid = self.request.query_params.get("company_uuid")
            return queryset.filter(company_id=company_uuid)
        return queryset

    def get_serializer_class(self):
        if self.action == "list":
            return ClientListSerializer
        return self.serializer_class

beyondtheadmin/clients/views/dashboard.py
import uuid

from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import DeleteView, ListView, TemplateView

from beyondtheadmin.dashboard.permissions import HasCompanyMixin
from beyondtheadmin.invoices.models import Invoice

from ..models import Client


def is_valid_uuid(val):
    try:
        uuid.UUID(str(val))
        return True
    except ValueError:
        return False


class ClientAppView(LoginRequiredMixin, HasCompanyMixin, TemplateView):
    template_name = "clients_app/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if "pk" in self.kwargs:
            context["client_id"] = self.kwargs["pk"]
            context["client"] = get_object_or_404(
                Client, pk=self.kwargs["pk"], company__users=self.request.user
            )
        invoice_param = self.request.GET.get("invoice", None)
        if invoice_param:
            context["redirect_to_invoice"] = 1
            if is_valid_uuid(invoice_param):
                try:
                    invoice = Invoice.objects.get(pk=invoice_param)
                    if not invoice.check_rights(self.request.user):
                        raise Invoice.DoesNotExist()
                    success_url = invoice.get_edit_url()
                except Invoice.DoesNotExist:
                    success_url = reverse_lazy("invoices:create")
            else:
                success_url = reverse_lazy("invoices:create")
        else:
            context["redirect_to_invoice"] = 0
            success_url = reverse_lazy("clients:list")
        context["success_url"] = success_url
        return context


class ClientDeleteView(LoginRequiredMixin, HasCompanyMixin, DeleteView):
    model = Client
    success_url = reverse_lazy("clients:list")
    template_name = "clients/confirm_delete.html"

    def get_queryset(self):
        return Client.objects.filter(company__users=self.request.user)


class ClientListView(LoginRequiredMixin, HasCompanyMixin, ListView):
    model = Client
    template_name = "clients/list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["has_multiple_companies"] = self.request.user.companies.count() > 1
        return context

    def get_queryset(self):
        return Client.objects.filter(company__users=self.request.user)

beyondtheadmin/companies/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, UpdateView

from .forms import CompanyForm
from .models import Company


class CompanyCreateView(LoginRequiredMixin, CreateView):
    model = Company
    form_class = CompanyForm
    template_name = 'companies/create.html'
    success_url = reverse_lazy('dashboard')

    def form_valid(self, form):
        """If the form is valid, save the associated model."""
        # noinspection PyAttributeOutsideInit
        self.object = form.save()
        self.object.users.add(self.request.user)
        return HttpResponseRedirect(self.get_success_url())


class CompanyDeleteView(LoginRequiredMixin, DeleteView):
    model = Company
    template_name = 'companies/confirm_delete.html'
    success_url = reverse_lazy('dashboard')

    def get_queryset(self):
        return super().get_queryset().filter(users=self.request.user)


class CompanyDetailView(LoginRequiredMixin, DetailView):
    model = Company
    template_name = 'companies/detail.html'

    def get_queryset(self):
        return super(CompanyDetailView, self).get_queryset().filter(users=self.request.user)\
                                                            .prefetch_related('invoices')


class CompanyUpdateView(LoginRequiredMixin, UpdateView):
    model = Company
    form_class = CompanyForm
    template_name = 'companies/update.html'
    success_url = reverse_lazy('dashboard')

    def get_queryset(self):
        return super().get_queryset().filter(users=self.request.user)

beyondtheadmin/companies/views/api_views.py
from django.core.files.base import ContentFile

from rest_framework import status, viewsets
from rest_framework.decorators import action
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from beyondtheadmin.users.models import User

from ..models import Company
from ..serializers import CompanyListSerializer, CompanySerializer, IDECompanySerializer
from ..utils.iban import OpenIban
from ..utils.zefix import get_detail, search_zefix


MAX_NB_SEARCH_RESULTS = 15
QUERY_MIN_LENGTH = 3


class CompanySearchView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request, *args, **kwargs):
        query_string = request.query_params.get("q")
        try:
            nb_results = int(request.query_params.get("nb"))
        except (ValueError, TypeError):
            nb_results = MAX_NB_SEARCH_RESULTS
        data = []
        if query_string and len(query_string) >= QUERY_MIN_LENGTH:
            data = search_zefix(query_string)
        serializer = IDECompanySerializer(data=data[:nb_results], many=True)
        serializer.is_valid()
        return Response(serializer.data)


class IBANSearchView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request, *args, **kwargs):
        query_string = request.query_params.get("q")
        data = []
        if query_string:
            data = OpenIban.validate_iban(query_string)
        return Response(data)


class CompanyDetailView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request, *args, **kwargs):
        query_string = request.query_params.get("uid")
        data = []
        if query_string:
            data = get_detail(query_string)
        data["country"] = "CH"
        serializer = IDECompanySerializer(data=data)
        serializer.is_valid()
        return Response(serializer.data)


class CompaniesViewSet(viewsets.ModelViewSet):
    permission_classes = [IsAuthenticated]
    serializer_class = CompanySerializer
    queryset = Company.objects.all()

    def get_serializer_class(self):
        if self.action == "list":
            return CompanyListSerializer
        return self.serializer_class

    def get_queryset(self):
        user: User = self.request.user
        return user.companies.all()

    def perform_create(self, serializer):
        company = serializer.save()
        company.users.add(self.request.user)

    def _update_file_for_field(self, request, field_name):
        company = self.get_object()
        file_name = request.headers.get("x-file-name")
        file_data = ContentFile(request.body)
        if getattr(company, field_name):
            response_status = status.HTTP_200_OK
        else:
            response_status = status.HTTP_201_CREATED
        getattr(company, field_name).save(file_name, file_data, save=True)
        return Response({}, status=response_status)

    @action(detail=True, methods=["put"])
    def update_logo(self, request, pk=None):
        return self._update_file_for_field(request, "logo")

    @action(detail=True, methods=["put"])
    def update_signature_image(self, request, pk=None):
        return self._update_file_for_field(request, "signature_image")

beyondtheadmin/companies/views/dashboard_views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, TemplateView, UpdateView

from ..forms import CompanyForm
from ..models import Company


class CompanyAppView(LoginRequiredMixin, TemplateView):
    template_name = "companies_app/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if "pk" in self.kwargs:
            context["company_id"] = self.kwargs["pk"]
            context["company"] = get_object_or_404(
                Company, pk=self.kwargs["pk"], users=self.request.user
            )
        return context


class CompanyCreateView(LoginRequiredMixin, CreateView):
    model = Company
    form_class = CompanyForm
    template_name = "companies/create.html"
    success_url = reverse_lazy("dashboard")

    def form_valid(self, form):
        """If the form is valid, save the associated model."""
        # noinspection PyAttributeOutsideInit
        self.object = form.save()
        self.object.users.add(self.request.user)
        return HttpResponseRedirect(self.get_success_url())


class CompanyDeleteView(LoginRequiredMixin, DeleteView):
    model = Company
    template_name = "companies/confirm_delete.html"
    success_url = reverse_lazy("dashboard")

    def get_queryset(self):
        return super().get_queryset().filter(users=self.request.user)

    def delete(self, request, *args, **kwargs):
        """
        Call the delete() method on the fetched object and then redirect to the
        success URL.
        """
        self.object: Company = self.get_object()
        success_url = self.get_success_url()
        self.object.set_deleted()
        return HttpResponseRedirect(success_url)


class CompanyDetailView(LoginRequiredMixin, DetailView):
    model = Company
    template_name = "companies/detail.html"

    def get_queryset(self):
        return super().get_queryset().filter(users=self.request.user).prefetch_related("invoices")


class CompanyUpdateView(LoginRequiredMixin, UpdateView):
    model = Company
    form_class = CompanyForm
    template_name = "companies/update.html"
    success_url = reverse_lazy("dashboard")

    def get_queryset(self):
        return super().get_queryset().filter(users=self.request.user)

beyondtheadmin/templates/base-base.html
{% load static i18n lang %}<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}beyondtheadmin{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  {% block lang_info %}{% hreflang_tags %}{% endblock lang_info %}

  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
  <![endif]-->

  <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">
  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/favicons/apple-touch-icon.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicons/favicon-32x32.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicons/favicon-16x16.png' %}">

  {% block css %}
    <!-- Latest compiled and minified Bootstrap CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://fonts.sandbox.google.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,300,0,0" />

    <link href="{% static 'css/sb-admin-2.css' %}" rel="stylesheet">
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
  {% endblock %}
</head>

<body {% block body-attrs %}{% endblock %}>
{% block main_content %}{% endblock %}

{% block modal %}{% endblock modal %}


{% block javascript %}

  <!-- bootstrap JS and its dependencies-->
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"
          integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
          integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
          crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"
          integrity="sha512-3j3VU6WC5rPQB4Ld1jnLV7Kd5xr+cq9avvhwqzbH/taCRNURoeEpoPBK9pDyeukwSxwRPJ8fDgvYXd6SkaZ2TA=="
          crossorigin="anonymous"></script>
  <!-- Your stuff: Third-party javascript libraries go here -->


  <!-- place project specific Javascript in this file -->

  <script defer type="module" src="{% static 'js/vendors.min.js' %}"></script>
  <script src="{% static 'js/project.js' %}"></script>
  <script src="{% static 'js/js.cookie.js' %}"></script>


{% endblock javascript %}
</body>
</html>

beyondtheadmin/templates/base.html
{% extends 'base-base.html' %}
{% load static i18n lang %}

{% block main_content %}
<div id="wrapper">
  <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion toggled" id="accordionSidebar">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
      <a class="nav-link" href="{% url 'dashboard' %}">
        <i class="bi bi-speedometer"></i>
        <span>{% trans "Dashboard" %}</span></a>
    </li>


    {% if user.has_company %}
    <!-- Divider -->
    <hr class="sidebar-divider">
    <!-- Heading -->
    <div class="sidebar-heading">
      {% trans "Invoices" %}
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
      <a class="nav-link" href="{% url 'invoices:create' %}" >
        <i class="bi bi-file-earmark-plus"></i>
        <span>{% trans "Add invoice" %}</span>
      </a>
    </li>

      <!-- Divider -->
    <hr class="sidebar-divider">
      <div class="sidebar-heading">
      {% trans "Clients" %}
    </div>

    <li class="nav-item">
      <a class="nav-link" href="{% url 'clients:list' %}" >
        <i class="bi bi-people"></i>
        <span>{% trans "All clients" %}</span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'clients:create' %}" >
        <i class="bi bi-person-plus"></i>
        <span>{% trans "Add Client" %}</span>
      </a>
    </li>
    {% endif %}
     <!-- Divider -->
    <hr class="sidebar-divider">

    {% if companies.count > 1 %}
      <div class="sidebar-heading">
      {% trans "Companies" %}
    </div>
     <!-- Heading -->

      {% for company in companies %}
        <li class="nav-item">
        <a class="nav-link" href="{{ company.get_absolute_url }}" >
          <i class="bi bi-building"></i>
          <span>{{ company }}</span>
        </a>
      </li>
      {% endfor %}
    {% endif %}

    <li class="nav-item">
      <a class="nav-link" href="{% url 'companies:create' %}" >
        <i class="bi bi-building-add"></i>

        <span>{% trans "Add company" %}</span>
      </a>
    </li>


    <!-- Divider -->
    <hr class="sidebar-divider">



    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
      <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>



  </ul>

  <div id="content-wrapper" class="d-flex flex-column">

    <!-- Main Content -->
    <div id="content">

      <!-- Topbar -->
      <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

        <!-- Sidebar Toggle (Topbar) -->
        <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
          <i class="bi bi-three-dots"></i>
        </button>


        <!-- Topbar Navbar -->
        <span class="brand">Beyond the admin</span>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item "><ul class="navbar-nav lang-chooser d-none d-lg-flex">{% lang_list %}</ul></li>
          <div class="topbar-divider d-none d-sm-block"></div>
          {% if request.user.is_authenticated %}
          <!-- Nav Item - User Information -->
          <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown"
               role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ request.user.name }}</span>
              <img class="img-profile rounded-circle" src="{% static 'images/undraw_profile.svg' %}">
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
              <a class="dropdown-item" href="{% url 'users:detail' username=request.user.username %}">
                <i class="bi bi-person-fill mr-2 text-gray-400"></i>
                {% trans "My profile" %}
              </a>
              {% if request.user.is_staff %}
                             <div class="dropdown-divider"></div>

                <a class="dropdown-item" href="{% url 'admin:index' %}">
                <i class="bi bi-window-dash mr-2 text-gray-400"></i>
                {% trans "Administration" %}
              </a>

              {% endif %}
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'account_logout' %}">
                <i class="bi bi-box-arrow-right mr-2 text-gray-400"></i>
                {% trans "Sign Out" %}
              </a>
            </div>
          </li>
{% endif %}
        </ul>

      </nav>
      <!-- End of Topbar -->

      <!-- Begin Page Content -->
      <div class="container-fluid p-0 p-sm-2">

        {% if messages %}
          {% for message in messages %}
            <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                  aria-hidden="true">&times;</span></button>
            </div>
          {% endfor %}
        {% endif %}

        {% block content %}
          <p>Use this document as a way to quick start any new project.</p>
        {% endblock content %}

        <!-- Page Heading
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
            <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>
        </div> -->


      </div>
      <!-- /.container-fluid -->

    </div>
    <!-- End of Main Content -->

    <!-- Footer -->
    <footer class="sticky-footer bg-white">
      <div class="container my-auto">
        <div class="copyright text-center my-auto">
          <span>Copyright © <a href="https://beyondthewall.ch">Beyond the wall</a> {% now "Y" %}</span>
        </div>
      </div>
    </footer>
    <!-- End of Footer -->

  </div>

</div>


{% endblock %}