beyondtheadmin/invoices/urls.py
from django.urls import path

from .views import dashboard as views


app_name = "invoices"
urlpatterns = [
    path("new/", view=views.InvoiceCreateView.as_view(), name="create"),
    path("<uuid:pk>/cancel", view=views.InvoiceCancelView.as_view(), name="cancel"),
    path(
        "<uuid:pk>/duplicate",
        view=views.InvoiceDuplicateView.as_view(),
        name="duplicate",
    ),
    path(
        "<uuid:pk>/send-reminder",
        view=views.InvoiceSendReminderEmailView.as_view(),
        name="reminder",
    ),
    path("<uuid:pk>/send", view=views.InvoiceSendMailView.as_view(), name="send"),
    path(
        "<uuid:pk>/mark-as-paid",
        view=views.InvoiceMarkPaidView.as_view(),
        name="mark_paid",
    ),
    path(
        "<uuid:pk>/mark-as-sent",
        view=views.InvoiceSnailMailUpdateView.as_view(),
        name="mark_sent",
    ),
    path("<uuid:pk>/update", view=views.InvoiceUpdateView.as_view(), name="update"),
    path("", view=views.InvoiceListView.as_view(), name="list"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

from rest_framework.authtoken.views import obtain_auth_token

from beyondtheadmin.dashboard.views import dashboard
from beyondtheadmin.invoices.views.public import InvoiceDetailView, qrbill


admin.autodiscover()
admin.site.enable_nav_sidebar = False

urlpatterns = i18n_patterns(
    path("", dashboard, name="dashboard"),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("clients/", include("beyondtheadmin.clients.urls", namespace="clients")),
    path("companies/", include("beyondtheadmin.companies.urls", namespace="companies")),
    path("invoices/", include("beyondtheadmin.invoices.urls", namespace="invoices")),
    path("users/", include("beyondtheadmin.users.urls", namespace="users")),
    prefix_default_language=False,
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    # Why is it here? invoices are translated to the client's language. We don't want to find ourselves
    # under a case where one could change the language. Therefore it has to find place here.
    path("invoice/<uuid:pk>/", view=InvoiceDetailView.as_view(), name="invoice-print"),
    path("invoice/<uuid:pk>/qrbill.svg", view=qrbill, name="qrbill"),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

beyondtheadmin/invoices/models.py
import datetime
from decimal import ROUND_UP, Decimal
from io import StringIO

from django.core.files.base import ContentFile
from django.db import models
from django.urls import reverse
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _

from ckeditor.fields import RichTextField
from dateutil.relativedelta import relativedelta
from model_utils import Choices
from model_utils.models import StatusModel
from qrbill.bill import QRBill

from beyondtheadmin.utils.model_utils import UUIDModel


class OpenInvoiceManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status__in=(Invoice.STATUS.sent, Invoice.STATUS.paid))


class Invoice(UUIDModel, StatusModel):
    STATUS = Choices(
        ("draft", _("Draft")),
        ("sent", _("Sent")),
        ("paid", _("Paid")),
        ("canceled", _("canceled")),
    )
    company = models.ForeignKey(
        "companies.Company",
        on_delete=models.PROTECT,
        related_name="invoices",
        null=True,
        blank=True,
        verbose_name=_("Company"),
    )
    client = models.ForeignKey(
        "clients.Client",
        on_delete=models.PROTECT,
        related_name="invoices",
        null=True,
        blank=True,
        verbose_name=_("Client"),
    )
    code = models.CharField(_("Code"), max_length=30, blank=True)
    due_date = models.DateField(_("Due date"), null=True, blank=True)
    displayed_date = models.DateField(_("Displayed date"), blank=True, null=True)
    vat_rate = models.DecimalField(
        _("VAT rate"),
        max_digits=6,
        decimal_places=4,
        default=Decimal("0.077"),
        blank=True,
    )
    total = models.DecimalField(
        _("Total"),
        max_digits=7,
        decimal_places=2,
        default=0.0,
        blank=True,
        editable=False,
    )

    title = models.CharField(_("Title"), max_length=100, blank=True)
    description = RichTextField(_("Description"), blank=True)
    period_start = models.DateField(_("Start of invoice period"), blank=True, null=True)
    period_end = models.DateField(_("End of invoice period"), blank=True, null=True)

    version = models.PositiveIntegerField(_("Version"), default=1, editable=False)

    qr_bill = models.TextField(_("QR Bill"), blank=True, null=True)
    sent_date = models.DateTimeField(_("Sent date"), blank=True, null=True)
    last_reminder_date = models.DateTimeField(_("Last reminder date"), blank=True, null=True)

    created_by = models.ForeignKey(
        "users.User",
        on_delete=models.SET_NULL,
        related_name="invoices_created",
        null=True,
        blank=True,
        verbose_name=_("Created by"),
    )

    objects = models.Manager()
    visible = OpenInvoiceManager()

    class Meta:
        ordering = ("-due_date",)

    def __str__(self):
        return self.code

    @property
    def display_country(self):
        return (
            self.company.country
            and self.client.country
            and self.company.country != self.client.country
        )

    @property
    def displayed_datetime(self):
        if self.due_date:
            return datetime.datetime(
                self.displayed_date.year,
                self.displayed_date.month,
                self.displayed_date.day,
            )
        return None

    @property
    def due_datetime(self):
        if self.due_date:
            return datetime.datetime(self.due_date.year, self.due_date.month, self.due_date.day)
        return None

    @property
    def is_draft(self):
        return self.status == self.STATUS.draft

    @property
    def is_sent(self):
        return self.status == self.STATUS.sent

    @property
    def is_paid(self):
        return self.status == self.STATUS.paid

    @property
    def is_ready(self):
        conditions = [
            self.displayed_date is not None,
            self.due_date is not None,
            self.company is not None,
            self.client is not None,
            self.title != "",
            self.period_start is None or self.period_end is not None,
            self.period_end is None or self.period_start is not None,
        ]
        return all(conditions) and self.lines.exists()

    @property
    def is_overdue(self):
        return self.status == self.STATUS.sent and self.due_date < now().date()

    @property
    def latest_pdf(self):
        try:
            return self.pdfs.get(version=self.version).pdf
        except InvoicePDF.DoesNotExist:
            return None

    @property
    def subtotal(self):
        acc = Decimal("0.0")
        for line in self.lines.all():
            acc += line.total
        return acc

    def add_pdf(self, content, version):
        invoice_pdf, created = InvoicePDF.objects.get_or_create(invoice=self, version=version)
        invoice_pdf.pdf.save(f"{self.code}.pdf", ContentFile(content), save=False)
        invoice_pdf.status = InvoicePDF.STATUS.ready
        invoice_pdf.save()

    def duplicate(self):
        previous_pk = self.pk
        self.pk = None
        self.code = ""
        self.displayed_date = now().date()
        self.due_date = self.displayed_date + relativedelta(days=self.client.payment_delay_days)
        if self.period_start:
            self.period_start = self.period_start + relativedelta(months=1)
        if self.period_end:
            self.period_end = self.period_end + relativedelta(months=1)
        self.status = Invoice.STATUS.draft
        self.version = 1
        self.pdf = None
        self.pdf_version = None
        self.qr_bill = None
        self.save(generate_code=False)
        assert previous_pk != self.pk
        for line in InvoiceLine.objects.filter(invoice_id=previous_pk):
            line.pk = None
            line.invoice = self
            line.save()
        return self

    def get_absolute_url(self):
        return reverse("invoice-print", kwargs={"pk": self.pk})

    def get_api_url(self):
        return reverse("api:invoice-detail", kwargs={"pk": self.pk})

    def get_api_lines_url(self):
        return reverse("api:invoices-lines-list", kwargs={"invoice_pk": self.pk})

    def get_cancel_url(self):
        return reverse("invoices:cancel", kwargs={"pk": self.pk})

    def get_code(self):
        return f"{self.client.slug}-{self.client.invoice_current_count + 1}"

    def get_duplicate_url(self):
        return reverse("invoices:duplicate", kwargs={"pk": self.pk})

    def get_edit_url(self):
        return reverse("invoices:update", kwargs={"pk": self.pk})

    def generate_latest_pdf(self):
        from .pdf import build_content_for_pdf, generate_pdf

        content = build_content_for_pdf(self)
        generated_pdf = generate_pdf(content)
        self.add_pdf(generated_pdf, self.version)

    def get_pdf_generation_url(self):
        return reverse(
            "api:invoices-pdf-detail",
            kwargs={"invoice_pk": self.pk, "version": self.version},
        )

    def get_qrbill(self):
        if not (self.due_date and self.company and self.client):
            raise ValueError
        return QRBill(
            account=self.company.iban,
            debtor={
                "name": self.client.name,
                "pcode": self.client.zip_code,
                "city": self.client.city,
                "country": self.client.country.code,
            },
            extra_infos=self.code,
            creditor={
                "name": self.company.bank_account_name,
                "street": self.company.address,
                "pcode": self.company.zip_code,
                "city": self.company.city,
                "country": self.company.country.code,
            },
            language=self.client.language,
            due_date=self.due_date.strftime("%Y-%m-%d"),
            amount=self.get_total(),
        )

    def get_qrbill_url(self):
        return reverse("qrbill", kwargs={"pk": self.pk})

    def get_reminder_url(self):
        return reverse("invoices:reminder", kwargs={"pk": self.pk})

    def get_set_paid_url(self):
        return reverse("invoices:mark_paid", kwargs={"pk": self.pk})

    def get_send_url(self):
        return reverse("invoices:send", kwargs={"pk": self.pk})

    def get_snail_mail_url(self):
        return reverse("invoices:mark_sent", kwargs={"pk": self.pk})

    def get_total(self):
        return self.subtotal + self.get_vat()

    def get_vat(self):
        return (self.subtotal * self.vat_rate).quantize(Decimal(".01"), rounding=ROUND_UP)

    def check_rights(self, user):
        if not self.company:
            return self.created_by == user
        return self.company in user.companies.all()

    def save(self, update_version=True, generate_code=False, *args, **kwargs):
        if not self.code and generate_code:
            self.code = self.get_code()
            self.client.invoice_current_count += 1
            self.client.save()
        if not self.displayed_date:
            self.displayed_date = self.created
        if update_version:
            self.total = self.get_total()
            self.version += 1
            try:
                qr_bill = self.get_qrbill()
                qr_io = StringIO()
                qr_bill.as_svg(qr_io, full_page=False)
                self.qr_bill = qr_io.getvalue()
            except ValueError:
                pass
        super().save(*args, **kwargs)

    def set_canceled(self):
        self.status = self.STATUS.canceled
        self.save(update_fields=["status"])

    def set_draft(self):
        self.status = self.STATUS.draft
        self.save(update_fields=["status"])

    def set_paid(self):
        self.status = self.STATUS.paid
        self.save(update_fields=["status"])

    def set_sent(self):
        self.status = self.STATUS.sent
        self.sent_date = now()
        self.save(update_fields=["status", "sent_date"])

    @staticmethod
    def get_overdue_query_params(values):

beyondtheadmin/invoices/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Div, Layout, Submit

from .models import Invoice


class BaseInvoiceForm(forms.ModelForm):
    class Meta:
        model = Invoice
        fields = ("company", "client")

    def __init__(self, *args, **kwargs):
        companies = kwargs.pop("companies", None)
        clients = kwargs.pop("clients", None)
        super().__init__(*args, **kwargs)
        if companies is not None:
            self.fields["company"].queryset = companies
        if clients is not None:
            self.fields["client"].queryset = clients
        self.helper = FormHelper()
        self.helper.add_input(Submit("submit", _("Submit")))


class InvoiceStatusForm(forms.ModelForm):
    class Meta:
        model = Invoice
        fields = ("status",)
        widgets = {"status": forms.HiddenInput}

    def __init__(self, *args, request=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.include_media = False
        self.helper.layout = Layout(
            "status",
            Div(
                Submit("save", _("Save")),
            ),
        )


class EmailForm(forms.Form):
    subject = forms.CharField(max_length=255)
    message = forms.CharField(widget=forms.Textarea)

    def __init__(self, *args, request=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.include_media = False

        self.helper.layout = Layout(
            "subject",
            "message",
            Div(
                Submit("save", _("Send")),
            ),
        )

beyondtheadmin/invoices/views.py
import io

from django.http import FileResponse, Http404
from django.utils.translation import ugettext as _
from django.views.generic import ListView, DetailView


from .models import Invoice


class InvoiceListView(ListView):
    model = Invoice
    template_name = 'invoices/list.html'


class InvoiceDetailView(DetailView):
    model = Invoice
    template_name = 'invoices/detail.html'


def qrbill(request, *args, **kwargs):
    try:
        invoice = Invoice.objects.get(pk=kwargs.get('pk'))
    except Invoice.DoesNotExist:
        raise Http404(_("Invoice does not exist"))
    if not invoice.qr_bill:
        raise Http404(_("Invoice has no QR Bill"))
    buffer = io.BytesIO(invoice.qr_bill.encode('utf-8'))
    return FileResponse(buffer, content_type='image/svg+xml',
                        as_attachment=True,
                        filename='{}.svg'.format(invoice.code))

beyondtheadmin/invoices/views/public.py
import io

from django.http import FileResponse, Http404
from django.utils.translation import gettext as _
from django.views.generic import DetailView

from ..models import Invoice


class InvoiceDetailView(DetailView):
    model = Invoice
    template_name = "invoices/detail.html"


# noinspection PyUnusedLocal
def qrbill(request, *args, **kwargs):
    try:
        invoice = Invoice.objects.get(pk=kwargs.get("pk"))
    except Invoice.DoesNotExist:
        raise Http404(_("Invoice does not exist"))
    if not invoice.qr_bill:
        raise Http404(_("Invoice has no QR Bill"))
    buffer = io.BytesIO(invoice.qr_bill.encode("utf-8"))
    return FileResponse(
        buffer,
        content_type="image/svg+xml",
        as_attachment=True,
        filename=f"{invoice.code}-qrbill.svg",
    )

beyondtheadmin/invoices/templates/invoices/confirm_cancel.html
{% extends "base.html" %}
{% load i18n crispy_forms_tags switzerland %}

{% block title %}{% trans "Send Invoice" %}{% endblock %}


{% block content %}
  <header class="page-header page-header-dark bg-gradient-primary">
    <div class="container">
      <div class="page-header-content pt-4">
        <div class="row align-items-center justify-content-between">
          <div class="col-auto mt-4">
            <h1 class="page-header-title">
              <i class="bi bi bi-credit-card"></i>&nbsp; {% trans "Cancel invoice" %}
            </h1>
            <div class="page-header-subtitle">
              {{ invoice.code }}
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>
  <section class="container headed-content">
    <div class="datatable card">
      <div class="card-body">
        <p class="lead">
        {% blocktrans with invoice=invoice.code client=invoice.client amount=invoice.total|money %}Please confirm you want to cancel invoice {{ invoice }} ({{ amount }}) for {{ client }}.{% endblocktrans %}
        </p>

        <form action="" method="post">
          {% crispy form %}
        </form>
      </div>
    </div>
  </section>
{% endblock content %}

beyondtheadmin/invoices/templates/invoices/confirm_paid.html
{% extends "base.html" %}
{% load i18n crispy_forms_tags switzerland %}

{% block title %}{% trans "Send Invoice" %}{% endblock %}


{% block content %}
  <header class="page-header page-header-dark bg-gradient-primary">
    <div class="container">
      <div class="page-header-content pt-4">
        <div class="row align-items-center justify-content-between">
          <div class="col-auto mt-4">
            <h1 class="page-header-title">
              <i class="bi bi bi-credit-card"></i>&nbsp; {% trans "Payment received" %}
            </h1>
            <div class="page-header-subtitle">
              {{ invoice.code }}
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>
  <section class="container headed-content">
    <div class="datatable card">
      <div class="card-body">
        <p class="lead">
        {% blocktrans with client=invoice.client amount=invoice.total|money %}Please confirm you've received {{ amount }} from {{ client }}.{% endblocktrans %}
        </p>

        <form action="" method="post">
          {% crispy form %}
        </form>
      </div>
    </div>
  </section>
{% endblock content %}

beyondtheadmin/invoices/templates/invoices/confirm_print.html
{% extends "base.html" %}
{% load i18n crispy_forms_tags %}

{% block title %}{% trans "Send Invoice" %}{% endblock %}


{% block content %}
  <header class="page-header page-header-dark bg-gradient-primary">
    <div class="container">
      <div class="page-header-content pt-4">
        <div class="row align-items-center justify-content-between">
          <div class="col-auto mt-4">
            <h1 class="page-header-title">
              <i class="bi bi-mailbox"></i>&nbsp; {% trans "Already sent" %}
            </h1>
            <div class="page-header-subtitle">
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>
  <section class="container headed-content">
    <div class="datatable card">
      <div class="card-body">

        <a href="{{ invoice.get_absolute_url }}?pdf=1" download="">
          <i class="bi bi-file-earmark-text"></i>&nbsp; {% trans "Download invoice" %}</a><br>
        <p class="lead">

          {% blocktrans with client=invoice.client %}Please confirm you've sent the invoice directly to {{ client }}.{% endblocktrans %}
        </p>

        <form action="{{ invoice.get_snail_mail_url }}" method="post">
          {% crispy form %}
        </form>
      </div>
    </div>
  </section>
{% endblock content %}

beyondtheadmin/invoices/templates/invoices/create.html
{% extends "base.html" %}
{% load i18n crispy_forms_tags %}

{% block title %}{% trans "Invoices" %}{% endblock %}


{% block content %}
  <header class="page-header page-header-dark bg-gradient-primary">
    <div class="container">
      <div class="page-header-content pt-4">
        <div class="row align-items-center justify-content-between">
          <div class="col-auto mt-4">
            <h1 class="page-header-title">
              {% trans "Create Invoice" %}
            </h1>
            <div class="page-header-subtitle">
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>
  <section class="container headed-content">
    <div class="datatable card">
      <div class="card-body">
      <form action="{% url "invoices:create" %}" method="post">
        {% crispy form %}
      </form>
      </div>
    </div>
  </section>
{% endblock content %}

beyondtheadmin/invoices/templates/invoices/send-reminder.html
{% extends "invoices/send.html" %}
{% load i18n crispy_forms_tags switzerland %}

{% block title %}{% trans "Send reminder" %}{% endblock %}
{% block pagetitle %}{% trans "Send reminder" %}{% endblock %}

{% block lead %}
  {% blocktrans with invoice=invoice.code client=invoice.client amount=invoice.total|money %}Please confirm you
    want to send a reminder for invoice {{ invoice }} ({{ amount }}) to {{ client }}.{% endblocktrans %}
{% endblock%}

beyondtheadmin/invoices/templates/invoices/update.html
{% extends "base.html" %}
{% load i18n l10n crispy_forms_tags %}

{% block title %}{% trans "Invoices" %}{% endblock %}


{% block content %}
  <header class="page-header page-header-dark bg-gradient-primary">
    <div class="container">
      <div class="page-header-content pt-4">
        <div class="row align-items-center justify-content-between">
          <div class="col-auto mt-4">
            <h1 class="page-header-title">
              {% blocktrans with invoice=invoice.code %}Invoice: {{ invoice }}{% endblocktrans %}
            </h1>
            <div class="page-header-subtitle">
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>
  <section class="container headed-content">
    <div class="datatable card">
      <div class="card-body">
        <form action="{{ invoice.get_edit_url }}" method="post">
          {% crispy form %}
        </form>
      </div>
    </div>
  </section>


  {% verbatim %}
  <script id="tpl-invoice-line" type="text/x-handlebars-template">
    <div id="item-{{ item.id }}" data-item-id="{{ item.id }}" data-item-url="{{ item.url }}" class="row invoice-line">
      <div class="col-4">
        <label for="description-{{ item.id }}" class="form-label">
          {% endverbatim %}{% trans "Description" %}{% verbatim %}
        </label>
        <textarea class="form-control description" id="description-{{ item.id }}"
                  rows="3">{{ item.description }}</textarea>
      </div>
      <div class="col">
        <label for="quantity-{{ item.id }}" class="form-label">
          {% endverbatim %}{% trans "Quantity" %}{% verbatim %}
        </label>
        <input type="number" step="any" value="{{ item.quantity }}" class="form-control quantity"
               id="quantity-{{ item.id }}">
      </div>
      <div class="col">
        <label for="unit-{{ item.id }}" class="form-label">
          {% endverbatim %}{% trans "Unit" %}{% verbatim %}
        </label>
        <select class="unit form-control" id="unit-{{ item.id }}">
          {{#select item.unit}}
          <option value="h">{% endverbatim %}{% trans "Hour" %}{% verbatim %}</option>
          <option value="nb">{% endverbatim %}{% trans "Number" %}{% verbatim %}</option>
          {{/select}}
        </select>
      </div>
      <div class="col">
        <label for="price_per_unit-{{ item.id }}" class="form-label">
          {% endverbatim %}{% trans "Unit price" %}{% verbatim %}
        </label>
        <input type="number" step=".01"
               value="{{ safeVal item.price_per_unit default_hourly_rate }}"
               class="form-control price_per_unit"
               id="price_per_unit-{{ item.id }}">
      </div>
      <div class="col">
        <label for="total-{{ item.id }}" class="form-label">
          {% endverbatim %}{% trans "Total" %}{% verbatim %}
        </label>
        <span class="form-text total" id="total-{{ item.id }}">{{ item.total }}</span>
      </div>
      <span class="item-action">
        <label>&nbsp;</label><br>
        <a href="" class="remove-line form-text"
           data-api-url="{{ item.url }}">{% endverbatim %}{% trans "Delete" %}{% verbatim %}</a>
      </span>
    </div>
  </script>
  {% endverbatim %}
{% endblock content %}

{% block javascript %}

  {{ block.super }}
  {{ form.media }}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.7.7/handlebars.min.js"></script>
  <script>
    jQuery(document).ready(function ($) {
      $.ajaxSetup({
        headers: {"X-CSRFToken": "{{ csrf_token }}"}
      });

      let updateDueDate = function () {
        let dateFormat = 'DD.MM.YYYY'
        let displayedDate = $('#id_displayed_date').val();

        if (displayedDate) {
          let dueDate = moment(displayedDate, dateFormat);
          dueDate.add({{ invoice.client.payment_delay_days }}, 'days')
          $('#id_due_date').val(dueDate.format(dateFormat));
        }
      };
      $('#id_displayed_date').datetimepicker().on('dp.change', updateDueDate);

      Handlebars.registerHelper("select", function (value, options) {
        return options.fn(this)
            .split('\n')
            .map(function (v) {
              let t = 'value="' + value + '"'
              return !RegExp(t).test(v) ? v : v.replace(t, t + ' selected="selected"')
            })
            .join('\n')
      });
      Handlebars.registerHelper('safeVal', function (value, safeValue) {
        let out = value || safeValue;
        return new Handlebars.SafeString(out);
      });


      const source = $("#tpl-invoice-line").html();
      let line_tmpl = Handlebars.compile(source);

      let getLines = function (data) {
        for (const line of data.results) {
          let html = line_tmpl(
              {
                'item': line,
                'default_hourly_rate': {{ invoice.client.default_hourly_rate|unlocalize }}
              }
          );
          $('.lines').append(html);
        }
      };

      let updateLine = function ($line) {
        updateTotal($line);
        let data = {
          'description': $('.description', $line).val(),
          'quantity': $('.quantity', $line).val(),
          'unit': $('.unit', $line).val(),
          'price_per_unit': $('.price_per_unit', $line).val(),
        }
        if ($line.data('item-url') !== '') {
          $.ajax({
            url: $line.data('item-url'),
            type: 'PUT',
            data: data,
            success: function(response) {
              console.log('saved')
            }
          });
        } else {
          $.ajax({
            url: '{{ invoice.get_api_url }}lines/',
            type: 'POST',
            data: data,
            success: function(response) {
              $line.data('item-url', response.url);
              $line.data('item-id', response.id);
              $line.attr('id', 'item-' + response.id);
            }
          });
        }
      };

      let updateTotal = function($line){
        if (!$('.quantity', $line).val() || !$('.price_per_unit', $line)) return;
        $('.total', $line).text(
            parseFloat($('.quantity', $line).val()) * parseFloat($('.price_per_unit', $line).val())
        )
      }

      $.ajax({
        url: "{{ invoice.get_api_url }}lines/",
        type: 'GET',
        success: function (response) {
          getLines(response);
        },
      });

      $('#add-line').on('click', function () {
        let html = line_tmpl(
            {
              'item': {},
              'default_hourly_rate': {{ invoice.client.default_hourly_rate|unlocalize }}
            });
        $('.lines').append(html);
      });

      $('.lines').on('change', '.invoice-line :input', function () {
        updateLine($(this).parents('.invoice-line'));
      });

      $('.lines').on('click', '.invoice-line .remove-line', function (event) {
        event.preventDefault();
        let $line = $(this).parents('.invoice-line');
        $.ajax({
          url: $(this).data('api-url'),
          type: 'DELETE',
          success: function (response) {
            $line.remove();
          }
        });
      });


    });

  </script>
{% endblock %}