beyondtheadmin/clients/urls.py
from django.urls import path

from .views.dashboard import ClientAppView, ClientDeleteView, ClientListView


app_name = "clients"
urlpatterns = [
    path("new", view=ClientAppView.as_view(), name="create"),
    path("<uuid:pk>/edit", view=ClientAppView.as_view(), name="update"),
    path("<uuid:pk>/delete", view=ClientDeleteView.as_view(), name="delete"),
    path("", view=ClientListView.as_view(), name="list"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

from rest_framework.authtoken.views import obtain_auth_token

from beyondtheadmin.dashboard.views import dashboard
from beyondtheadmin.invoices.views.public import InvoiceDetailView, qrbill


admin.autodiscover()
admin.site.enable_nav_sidebar = False

urlpatterns = i18n_patterns(
    path("", dashboard, name="dashboard"),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("clients/", include("beyondtheadmin.clients.urls", namespace="clients")),
    path("companies/", include("beyondtheadmin.companies.urls", namespace="companies")),
    path("invoices/", include("beyondtheadmin.invoices.urls", namespace="invoices")),
    path("users/", include("beyondtheadmin.users.urls", namespace="users")),
    prefix_default_language=False,
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    # Why is it here? invoices are translated to the client's language. We don't want to find ourselves
    # under a case where one could change the language. Therefore it has to find place here.
    path("invoice/<uuid:pk>/", view=InvoiceDetailView.as_view(), name="invoice-print"),
    path("invoice/<uuid:pk>/qrbill.svg", view=qrbill, name="qrbill"),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

beyondtheadmin/companies/models.py
from decimal import Decimal

from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from ckeditor.fields import RichTextField
from colorfield.fields import ColorField
from django_countries.fields import CountryField
from localflavor.generic.models import BICField, IBANField
from model_utils import Choices
from model_utils.models import TimeStampedModel
from phonenumber_field.modelfields import PhoneNumberField

from beyondtheadmin.utils.model_utils import UUIDModel


STATUS = Choices(
    ("active", _("Active")),
    ("inactive", _("Inactive")),
)


class ActiveCompanyManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=STATUS.active)


class Company(UUIDModel):
    name = models.CharField(_("Company name"), max_length=255)
    address = models.TextField(_("Address"), blank=True)
    zip_code = models.CharField(_("Postal code"), max_length=10, blank=True)
    city = models.CharField(_("City"), max_length=255, blank=True)
    country = CountryField(_("Country"), blank=True, null=True)

    phone = PhoneNumberField(_("Phone number"), blank=True)
    additional_phone = PhoneNumberField(_("Additional phone number"), blank=True)

    email = models.EmailField(_("Email"), blank=True)
    website = models.URLField(_("Web site"), blank=True)
    enable_vat = models.BooleanField(_("Enable VAT"), default=True)
    vat_id = models.CharField(_("VAT ID"), blank=True, max_length=20)
    vat_rate = models.DecimalField(
        _("VAT rate"),
        max_digits=6,
        decimal_places=4,
        default=Decimal("0.077"),
        blank=True,
    )
    default_hourly_rate = models.DecimalField(
        _("Hourly rate"), max_digits=6, decimal_places=2, default=Decimal("0.00")
    )
    payment_delay_days = models.IntegerField(
        _("Payment delay"), help_text=_("Default delay in days to due date"), default=30
    )

    name_for_bank = models.CharField(_("Bank account's owner name"), max_length=255, blank=True)
    bank = models.TextField(_("Bank"), blank=True)
    bic = BICField(_("BIC"), blank=True)
    iban = IBANField(_("IBAN"), blank=True)

    logo = models.ImageField(_("Logo"), blank=True, null=True)
    contrast_color = ColorField(_("Contrast color"), default="#3B4451")

    signature_text = models.CharField(_("Signature as text"), max_length=100, blank=True)
    signature_image = models.ImageField(_("Signature as image"), null=True, blank=True)
    email_signature = models.TextField(_("Email signature"), blank=True)
    invoice_note = RichTextField(
        _("Notes"),
        blank=True,
        help_text=_("Displayed between banking details and signature"),
    )

    override_default_from_email = models.BooleanField(
        _("Override default from email"), default=False
    )
    from_email = models.CharField(
        _("From email"),
        max_length=255,
        blank=True,
    )
    bcc_email = models.EmailField(
        _("Copy of invoices"),
        help_text=_("Email address that will receive every sent invoice in bcc"),
        blank=True,
    )
    thanks = models.TextField(
        _("Thanks"),
        blank=True,
        help_text=_(
            "Thanks at bottom of invoice. If set, this will be on every invoice, regardless of language"
        ),
    )
    status = models.CharField(
        _("Status"),
        max_length=20,
        choices=STATUS,
        default=STATUS.active,
    )
    objects = ActiveCompanyManager()
    all_objects = models.Manager()

    class Meta:
        ordering = ("name", "created")
        verbose_name = _("Company")
        verbose_name_plural = _("Companies")

    def __str__(self):
        return self.name

    @property
    def api_url(self):
        return reverse("api:company-detail", kwargs={"pk": self.pk})

    @property
    def all_invoices_api_url(self):
        return reverse("api:company-invoices", kwargs={"company_pk": self.pk})

    @property
    def bank_account_name(self):
        return self.name_for_bank or self.name

    @property
    def create_invoice_url(self):
        return reverse("invoices:create") + f"?company={self.pk}"

    @property
    def delete_url(self):
        return reverse("companies:delete", kwargs={"pk": self.pk})

    @property
    def earnings_api_url(self):
        return reverse("api:earnings-per-company", kwargs={"company_pk": self.pk})

    @property
    def detail_url(self):
        return reverse("companies:detail", kwargs={"pk": self.pk})

    @property
    def edit_url(self):
        return reverse("companies:update", kwargs={"pk": self.pk})

    @property
    def has_signature(self):
        return bool(self.signature_text or self.signature_image)

    @property
    def invoice_from_email(self):
        if self.override_default_from_email:
            return self.from_email
        return f"{self.name} <{settings.DEFAULT_INVOICE_FROM_EMAIL}>"

    @property
    def open_invoices_api_url(self):
        return reverse("api:open-invoices-per-company", kwargs={"company_pk": self.pk})

    @property
    def single_line_address(self):
        output = []
        if self.address:
            output.append(self.address)
        if self.zip_code:
            output.append(f"{self.zip_code} {self.city}")
        if self.country:
            output.append(self.country.name)
        return ", ".join(output)

    def set_deleted(self):
        self.status = STATUS.inactive
        self.save()

    def open_invoices(self):
        from beyondtheadmin.invoices.models import Invoice

        return Invoice.visible.filter(company=self).select_related("client")

    def latest_open_invoices(self):
        return self.open_invoices().order_by("-due_date")[:5]

    def get_absolute_url(self):
        return self.detail_url


class Bank(TimeStampedModel):
    name = models.CharField(_("Bank name"), max_length=255)
    code = models.IntegerField(_("Code"), null=True)
    swift = models.CharField(_("BIC/Swift"), blank=True, max_length=11)

    address = models.TextField(_("Address"), blank=True)
    zip_code = models.CharField(_("Postal code"), max_length=10, blank=True)
    city = models.CharField(_("City"), max_length=255, blank=True)
    country = CountryField(_("Country"), blank=True, null=True)

    class Meta:
        ordering = ("name", "created")
        verbose_name = _("Bank")
        verbose_name_plural = _("Banks")

    def __str__(self):
        return self.name

beyondtheadmin/clients/views/dashboard.py
import uuid

from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import DeleteView, ListView, TemplateView

from beyondtheadmin.dashboard.permissions import HasCompanyMixin
from beyondtheadmin.invoices.models import Invoice

from ..models import Client


def is_valid_uuid(val):
    try:
        uuid.UUID(str(val))
        return True
    except ValueError:
        return False


class ClientAppView(LoginRequiredMixin, HasCompanyMixin, TemplateView):
    template_name = "clients_app/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if "pk" in self.kwargs:
            context["client_id"] = self.kwargs["pk"]
            context["client"] = get_object_or_404(
                Client, pk=self.kwargs["pk"], company__users=self.request.user
            )
        invoice_param = self.request.GET.get("invoice", None)
        if invoice_param:
            context["redirect_to_invoice"] = 1
            if is_valid_uuid(invoice_param):
                try:
                    invoice = Invoice.objects.get(pk=invoice_param)
                    if not invoice.check_rights(self.request.user):
                        raise Invoice.DoesNotExist()
                    success_url = invoice.get_edit_url()
                except Invoice.DoesNotExist:
                    success_url = reverse_lazy("invoices:create")
            else:
                success_url = reverse_lazy("invoices:create")
        else:
            context["redirect_to_invoice"] = 0
            success_url = reverse_lazy("clients:list")
        context["success_url"] = success_url
        return context


class ClientDeleteView(LoginRequiredMixin, HasCompanyMixin, DeleteView):
    model = Client
    success_url = reverse_lazy("clients:list")
    template_name = "clients/confirm_delete.html"

    def get_queryset(self):
        return Client.objects.filter(company__users=self.request.user)


class ClientListView(LoginRequiredMixin, HasCompanyMixin, ListView):
    model = Client
    template_name = "clients/list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["has_multiple_companies"] = self.request.user.companies.count() > 1
        return context

    def get_queryset(self):
        return Client.objects.filter(company__users=self.request.user)

beyondtheadmin/companies/views/dashboard_views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, TemplateView, UpdateView

from ..forms import CompanyForm
from ..models import Company


class CompanyAppView(LoginRequiredMixin, TemplateView):
    template_name = "companies_app/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if "pk" in self.kwargs:
            context["company_id"] = self.kwargs["pk"]
            context["company"] = get_object_or_404(
                Company, pk=self.kwargs["pk"], users=self.request.user
            )
        return context


class CompanyCreateView(LoginRequiredMixin, CreateView):
    model = Company
    form_class = CompanyForm
    template_name = "companies/create.html"
    success_url = reverse_lazy("dashboard")

    def form_valid(self, form):
        """If the form is valid, save the associated model."""
        # noinspection PyAttributeOutsideInit
        self.object = form.save()
        self.object.users.add(self.request.user)
        return HttpResponseRedirect(self.get_success_url())


class CompanyDeleteView(LoginRequiredMixin, DeleteView):
    model = Company
    template_name = "companies/confirm_delete.html"
    success_url = reverse_lazy("dashboard")

    def get_queryset(self):
        return super().get_queryset().filter(users=self.request.user)

    def delete(self, request, *args, **kwargs):
        """
        Call the delete() method on the fetched object and then redirect to the
        success URL.
        """
        self.object: Company = self.get_object()
        success_url = self.get_success_url()
        self.object.set_deleted()
        return HttpResponseRedirect(success_url)


class CompanyDetailView(LoginRequiredMixin, DetailView):
    model = Company
    template_name = "companies/detail.html"

    def get_queryset(self):
        return super().get_queryset().filter(users=self.request.user).prefetch_related("invoices")


class CompanyUpdateView(LoginRequiredMixin, UpdateView):
    model = Company
    form_class = CompanyForm
    template_name = "companies/update.html"
    success_url = reverse_lazy("dashboard")

    def get_queryset(self):
        return super().get_queryset().filter(users=self.request.user)

beyondtheadmin/dashboard/templates/dashboard/dashboard.html
{% extends 'base.html' %}
{% load i18n switzerland humanize %}
{% block content %}
  {% if not companies %}
    <section class="card card-header-actions mb-4">
      <header class="card-header ">
        {% trans "Companies" %}
        <a class="btn btn-sm btn-primary" type="button"
           href="{% url 'companies:create' %}">{% trans "Add company" %}</a>
      </header>
      <article class="card-body">
        {% if not companies %}
          <p class="lead">{% trans "You haven't defined a company yet. Please create at least one" %}</p>
          <form action="{% url 'companies:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% include "companies/form.html" with form=company_form %}
          </form>
        {% else %}
        {% endif %}
      </article>
    </section>
  {% endif %}

  <div class="row">
    {% for company in companies %}
      <div class="col-lg-6">
        <section class="card shadow card-header-actions mb-4">
          <header class="card-header ">
            {{ company.name }}
            <a href="{{ company.edit_url }}" class="btn btn-sm btn-primary"><i
              class="icon bi-pencil"></i> {% trans "Edit" %}</a>

          </header>
          <article class="card-body p-2 p-sm-2">
            <div class="row mb-4">
              <div class="col">
                <div class="small">{{ company.name }}</div>
                <div class="text-xs text-muted">{{ company.zip_code }} {{ company.city }}</div>
              </div>
              <div class="col">
                {% if company.logo %}
                  <div class="text-center">
                    <img src="{{ company.logo.url }}" class="img-fluid px-3 px-sm-4"/>
                  </div>
                {% endif %}</div>

            </div>
            <hr/>
            <h5 class="h6">{% trans "Open invoices" %}</h5>
            <main class="row open-invoices" data-url="{{ company.open_invoices_api_url }}">
              <div class="col-6 col-sm-9 col-lg-8 col-xl-9">
                <canvas style="position: relative; height: 3rem; width: 100%"></canvas>
              </div>
              <div class="col-6 col-sm-3 col-lg-4 col-xl-3 align-middle text-center">
                <div class="open-total h5 m font-weight-bold text-gray-800"></div>
              </div>
            </main>
          </article>
          <article class="pl-0 pr-0 pl-sm-2 pr-sm-2">
            <table class="table small">
              <thead>
              <tr class="d-lg-none d-xl-table-row">
                <th>{% trans "Client" %}<span class="d-lg-none d-xl-inline">/ {% trans "Code" %}</span></th>
                <th class="d-none d-sm-table-cell">{% trans "Due date" context "compact" %}</th>
                <th>{% trans "Amount" %}<span class="d-lg-none d-xl-inline">/ {% trans "Status" %}</span></th>
                <th><span class="d-lg-none d-xl-inline">{% trans "Actions" %}</span></th>

              </tr>
              </thead>
              {% for invoice in company.open_invoices|slice:":5" %}
                <tr>
                  <td
                    class="border-left-{% if invoice.is_paid %}success{% elif invoice.is_overdue %}danger{% elif invoice.is_sent %}primary{% else %}secondary{% endif %}">
                    <span class="d-lg-none d-xl-inline">{{ invoice.client }}<br></span>
                    <small>{{ invoice.code }}</small>
                  </td>
                  <td class="d-none d-sm-table-cell">{{ invoice.due_date|date }}<br>
                    {% if invoice.due_date and not invoice.is_paid %}
                      <small class="d-none d-sm-inline">{{ invoice.due_datetime | naturaltime }}</small>
                    {% endif %}
                  </td>
                  <td>
                    {{ invoice.total|money }}<br>
                    <small>{{ invoice.get_status_display }}</small>
                  </td>
                  <td class="text-nowrap">
                    {% if invoice.is_sent %}
                      <a href="{{ invoice.get_set_paid_url }}" class="btn btn-sm">
                        <i class="icon bi-credit-card"></i>
                        <span
                          class="d-inline d-sm-none d-xl-inline">&nbsp;{% trans "Payment received" context "compact" %}</span>
                      </a><br>
                    {% endif %}
                    <a href="{{ invoice.get_duplicate_url }}" class="btn btn-sm">
                      <i class="icon bi-files"></i>
                      <span class="d-inline d-sm-none d-xl-inline">&nbsp;{% trans "Duplicate" %}</span>
                    </a><br>
                    <a href="{{ invoice.get_absolute_url }}" class="btn btn-sm no-">
                      <i class="icon bi-file-earmark-text"></i>
                      <span class="d-inline d-sm-none d-xl-inline">&nbsp;{% trans "View" %}</span>
                    </a>
                  </td>
                </tr>
              {% endfor %}

            </table>
          </article>

          <a class="card-footer" href="{{ company.get_absolute_url }}">
            <div class="d-flex align-items-center justify-content-between small text-body">
              {% trans "Details" %}
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                   stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                   class="feather feather-arrow-right">
                <line x1="5" y1="12" x2="19" y2="12"></line>
                <polyline points="12 5 19 12 12 19"></polyline>
              </svg>
            </div>
          </a>
        </section>

      </div>
    {% endfor %}
  </div>

{% endblock content %}

{% block javascript %}
  {{ block.super }}
  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3"></script>
  <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datasource@0.1.0"></script>
  <script>
    jQuery(document).ready(function ($) {
      $.ajaxSetup({
        headers: {"X-CSRFToken": "{{ csrf_token }}"}
      });
      let number_format = function (number, decimals, dec_point, thousands_sep) {
        // *     example: number_format(1234.56, 2, ',', ' ');
        // *     return: '1 234,56'
        number = (number + '').replace(',', '').replace(' ', '');
        let n = !isFinite(+number) ? 0 : +number,
          prec = !isFinite(+decimals) ? 0 : Math.abs(decimals),
          sep = (typeof thousands_sep === 'undefined') ? "'" : thousands_sep,
          dec = (typeof dec_point === 'undefined') ? '.' : dec_point,
          s = '',
          toFixedFix = function (n, prec) {
            let k = Math.pow(10, prec);
            return '' + Math.round(n * k) / k;
          };
        // Fix for IE parseFloat(0.55).toFixed(0) = 0;
        s = (prec ? toFixedFix(n, prec) : '' + Math.round(n)).split('.');
        if (s[0].length > 3) {
          s[0] = s[0].replace(/\B(?=(?:\d{3})+(?!\d))/g, sep);
        }
        if ((s[1] || '').length < prec) {
          s[1] = s[1] || '';
          s[1] += new Array(prec - s[1].length + 1).join('0');
        }
        return s.join(dec);
      }

      let updateOpenInvoices = function () {
        $('.open-invoices').each(function () {
          let url = $(this).data('url');
          let $total = $('.open-total', $(this));
          let ctx = $('canvas', this)[0].getContext('2d');
          $.ajax({
            url: url,
            type: 'get',
            success: function (response) {
              $total.text('CHF ' + number_format(response.total))
              let chart = new Chart(ctx, {
                  type: 'horizontalBar',
                  data: {
                    datasets: [
                      {
                        data: [response.waiting],
                        label: "{% trans 'Waiting' %}",
                        borderColor: 'rgba(78, 115, 223, 1)',
                        borderWidth: 1,
                        backgroundColor: 'rgba(78, 115, 223, 0.5)'
                      },
                      {
                        data: [response.overdue],
                        label: "{% trans 'Overdue' %}",
                        borderColor: 'rgba(231,74,59,1)',
                        borderWidth: 1,
                        backgroundColor: 'rgba(231,74,59,0.5)'
                      }
                    ]
                  },
                  options: {
                    legend: {
                      display: false,
                    },
                    tooltips: {
                      backgroundColor: "rgb(255,255,255)",
                      bodyFontColor: "#858796",
                      borderColor: '#dddfeb',
                      borderWidth: 1,
                      xPadding: 15,
                      yPadding: 15,
                      displayColors: true,
                      caretPadding: -10,
                      callbacks: {
                        label: function (tooltipItem, data) {
                          let label = data.datasets[tooltipItem.datasetIndex].label || '';
                          if (label) {
                            label += ': ';
                          }
                          label += 'CHF ' + number_format(tooltipItem.xLabel);
                          return label
                        },
                        title: function () {
                          return ''
                        },
                      }
                    },
                    scales: {
                      xAxes: [{
                        ticks: {
                          beginAtZero: true,
                          fontFamily: "Nunito, sans-serif",
                          fontSize: 11,
                        },
                        scaleLabel: {
                          display: false
                        },
                        gridLines: {},
                        stacked: true
                      }],
                      yAxes: [{
                        gridLines: {
                          display: false,
                          color: "#fff",
                          zeroLineColor: "#fff",
                          zeroLineWidth: 0
                        },
                        ticks: {
                          fontFamily: "Nunito, sans-serif",
                          fontSize: 11,
                        },
                        stacked: true
                      }]
                    },
                  }
                }
              )
            }
          })

        });
      };
      updateOpenInvoices()

    });
  </script>
{% endblock %}