beyondtheadmin/clients/urls.py
from django.urls import path

from .views.dashboard import ClientAppView, ClientDeleteView, ClientListView


app_name = "clients"
urlpatterns = [
    path("new", view=ClientAppView.as_view(), name="create"),
    path("<uuid:pk>/edit", view=ClientAppView.as_view(), name="update"),
    path("<uuid:pk>/delete", view=ClientDeleteView.as_view(), name="delete"),
    path("", view=ClientListView.as_view(), name="list"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

from rest_framework.authtoken.views import obtain_auth_token

from beyondtheadmin.dashboard.views import dashboard
from beyondtheadmin.invoices.views.public import InvoiceDetailView, qrbill


admin.autodiscover()
admin.site.enable_nav_sidebar = False

urlpatterns = i18n_patterns(
    path("", dashboard, name="dashboard"),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("clients/", include("beyondtheadmin.clients.urls", namespace="clients")),
    path("companies/", include("beyondtheadmin.companies.urls", namespace="companies")),
    path("invoices/", include("beyondtheadmin.invoices.urls", namespace="invoices")),
    path("users/", include("beyondtheadmin.users.urls", namespace="users")),
    prefix_default_language=False,
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    # Why is it here? invoices are translated to the client's language. We don't want to find ourselves
    # under a case where one could change the language. Therefore it has to find place here.
    path("invoice/<uuid:pk>/", view=InvoiceDetailView.as_view(), name="invoice-print"),
    path("invoice/<uuid:pk>/qrbill.svg", view=qrbill, name="qrbill"),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

beyondtheadmin/clients/models.py
from decimal import Decimal

from django.db import models
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

from django_countries.fields import CountryField
from model_utils import Choices

from beyondtheadmin.utils.model_utils import UUIDModel


class Client(UUIDModel):
    TYPES = Choices(("company", _("Company")), ("person", _("Person")))
    client_type = models.CharField(
        _("Client type"), choices=TYPES, default=TYPES.company, max_length=10
    )

    company_name = models.TextField(_("Name"), blank=True)

    contact_first_name = models.CharField(_("Contact first name"), max_length=255, blank=True)
    contact_last_name = models.CharField(_("Contact last name"), max_length=255, blank=True)
    contact_email = models.EmailField(_("Contact email"), blank=True)

    address = models.TextField(_("Address"), blank=True)
    zip_code = models.CharField(_("Postal code"), max_length=10, blank=True)
    city = models.CharField(_("City"), max_length=255, blank=True)
    country = CountryField(_("Country"), blank=True, null=True, default="CH")

    language = models.CharField(
        _("Language"),
        max_length=2,
        choices=(
            ("en", "English"),
            ("de", "Deutsch"),
            ("fr", "Français"),
            ("it", "Italiano"),
        ),
        default="fr",
    )
    currency = models.CharField(
        _("Currency"),
        max_length=3,
        choices=(("CHF", "CHF"), ("EUR", "Euro")),
        default="CHF",
    )
    payment_delay_days = models.IntegerField(
        _("Payment delay"), help_text=_("Default delay in days to due date"), default=30
    )
    vat_rate = models.DecimalField(
        _("VAT rate"),
        max_digits=6,
        decimal_places=4,
        default=Decimal("0.077"),
        blank=True,
    )
    default_hourly_rate = models.DecimalField(
        _("Default hourly rate"), max_digits=5, decimal_places=2, default="0.00"
    )

    email_template = models.TextField(
        verbose_name=_("Email Template"),
        help_text=_(
            "Default text for invoices sent by mail. Use double curly braces {{ and }} as delimiters for variables."
        ),
        blank=True,
    )

    slug = models.CharField(
        _("Slug"), help_text=_("Used to generate invoice code"), max_length=15, blank=True
    )
    invoice_current_count = models.IntegerField(
        _("Current count of invoices"),
        help_text=_("Used to generate invoice code"),
        default=0,
    )
    company = models.ForeignKey(
        verbose_name=_("Company"),
        to="companies.Company",
        related_name="clients",
        on_delete=models.CASCADE,
    )

    class Meta:
        ordering = ("company_name", "contact_last_name", "country")

    @property
    def api_url(self):
        return reverse_lazy("api:client-detail", kwargs={"pk": self.pk})

    @property
    def dashboard_url(self):
        return reverse_lazy("clients:update", kwargs={"pk": self.pk})

    @property
    def create_invoice_url(self):
        return reverse_lazy("invoices:create") + f"?client={self.pk}"

    @property
    def name(self):
        if self.is_company:
            return self.company_name
        return self.contact_fullname

    @property
    def contact_fullname(self):
        if self.contact_last_name:
            return f"{self.contact_first_name} {self.contact_last_name}"
        return self.contact_first_name

    @property
    def full_contact_email(self):
        if self.contact_fullname:
            return f"{self.contact_fullname} <{self.contact_email}>"
        return ""

    @property
    def is_company(self):
        return self.client_type == self.TYPES.company

    @property
    def is_person(self):
        return self.client_type == self.TYPES.person

    @property
    def last_invoice_date(self):
        last_invoice = self.invoices.order_by("displayed_date").last()
        if last_invoice:
            return last_invoice.displayed_date
        return None

    def get_absolute_url(self):
        return reverse_lazy("clients:update", kwargs={"pk": self.pk})

    def get_delete_url(self):
        return reverse_lazy("clients:delete", kwargs={"pk": self.pk})

    def get_update_url(self):
        return self.get_absolute_url()

    def __str__(self):
        return (
            self.client_type == self.TYPES.company and self.company_name or self.contact_fullname
        )

beyondtheadmin/clients/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from .forms import ClientForm
from .models import Client


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy("clients:list")
    template_name = "clients/create.html"

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    success_url = reverse_lazy("clients:list")
    template_name = "clients/confirm_delete.html"

    def get_queryset(self):
        return Client.objects.filter(company__users=self.request.user)


class ClientListView(LoginRequiredMixin, ListView):
    model = Client
    template_name = "clients/list.html"

    def get_queryset(self):
        return Client.objects.filter(company__users=self.request.user)


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy("clients:list")
    template_name = "clients/update.html"

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def get_queryset(self):
        return Client.objects.filter(company__users=self.request.user)

beyondtheadmin/clients/views/api.py
from rest_framework import viewsets
from rest_framework.authentication import SessionAuthentication

from beyondtheadmin.api.permissions import IsCompanyOwnedByUser

from ..models import Client
from ..serializers import ClientListSerializer, ClientSerializer


class ClientViewSet(viewsets.ModelViewSet):
    queryset = Client.objects.all()
    serializer_class = ClientSerializer
    permission_classes = [IsCompanyOwnedByUser]
    authentication_classes = [SessionAuthentication]

    def get_queryset(self):
        queryset = super().get_queryset().filter(company__users=self.request.user)
        if "company_uuid" in self.request.query_params:
            company_uuid = self.request.query_params.get("company_uuid")
            return queryset.filter(company_id=company_uuid)
        return queryset

    def get_serializer_class(self):
        if self.action == "list":
            return ClientListSerializer
        return self.serializer_class

beyondtheadmin/clients/views/dashboard.py
import uuid

from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import DeleteView, ListView, TemplateView

from beyondtheadmin.dashboard.permissions import HasCompanyMixin
from beyondtheadmin.invoices.models import Invoice

from ..models import Client


def is_valid_uuid(val):
    try:
        uuid.UUID(str(val))
        return True
    except ValueError:
        return False


class ClientAppView(LoginRequiredMixin, HasCompanyMixin, TemplateView):
    template_name = "clients_app/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if "pk" in self.kwargs:
            context["client_id"] = self.kwargs["pk"]
            context["client"] = get_object_or_404(
                Client, pk=self.kwargs["pk"], company__users=self.request.user
            )
        invoice_param = self.request.GET.get("invoice", None)
        if invoice_param:
            context["redirect_to_invoice"] = 1
            if is_valid_uuid(invoice_param):
                try:
                    invoice = Invoice.objects.get(pk=invoice_param)
                    if not invoice.check_rights(self.request.user):
                        raise Invoice.DoesNotExist()
                    success_url = invoice.get_edit_url()
                except Invoice.DoesNotExist:
                    success_url = reverse_lazy("invoices:create")
            else:
                success_url = reverse_lazy("invoices:create")
        else:
            context["redirect_to_invoice"] = 0
            success_url = reverse_lazy("clients:list")
        context["success_url"] = success_url
        return context


class ClientDeleteView(LoginRequiredMixin, HasCompanyMixin, DeleteView):
    model = Client
    success_url = reverse_lazy("clients:list")
    template_name = "clients/confirm_delete.html"

    def get_queryset(self):
        return Client.objects.filter(company__users=self.request.user)


class ClientListView(LoginRequiredMixin, HasCompanyMixin, ListView):
    model = Client
    template_name = "clients/list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["has_multiple_companies"] = self.request.user.companies.count() > 1
        return context

    def get_queryset(self):
        return Client.objects.filter(company__users=self.request.user)

beyondtheadmin/clients/templates/clients/confirm_delete.html
{% extends 'base.html' %}
{% load i18n  %}
{% block content %}
  <section class="card card-header-actions mb-4">
    <header class="card-header ">
      {% trans "Delete client" %}
    </header>
    <article class="card-body">
      <p class="lead">
        {% blocktrans with company=company %}Are you sure you want to delete "{{ client }}"?{% endblocktrans %}
      </p>
      <form action="{{ client.delete_url }}" method="post">
          {% csrf_token %}
          <button type="submit" class="btn btn-danger">{% trans "Confirm" %}</button>

        </form>
    </article>
  </section>

{% endblock content %}

beyondtheadmin/clients/templates/clients/create.html
{% extends 'base.html' %}
{% load i18n static %}
{% block content %}
  <section class="card card-header-actions mb-4">
    <header class="card-header ">
      {% trans "Create client" %}
    </header>
    <article class="card-body">
      <form action="{% url 'clients:create' %}" method="post" enctype="multipart/form-data">
        {% include "clients/form.html" %}
      </form>
    </article>
  </section>

{% endblock content %}

{% block javascript %}
{{ block.super }}
{{ form.media }}
{% endblock javascript %}

beyondtheadmin/clients/templates/clients/create_and_update_app.html
{% extends 'base.html' %}
{% load i18n static %}
{% block content %}
  <section class="card card-header-actions mb-4" id="app">
    <header class="card-header ">
      {% trans "Create client" %}
    </header>
    <article class="card-body">

    </article>
  </section>

{% endblock content %}

{% block javascript %}
{{ block.super }}
  <script src="{% static "clients_app/js/chunk-vendors.062285b0.js" %}" type="application/javascript"></script>

<script src="{% static 'clients_app/js/app.4c5a50c5.js' %}" type="application/javascript"></script>
{% endblock javascript %}

beyondtheadmin/clients/templates/clients/form.html
{% load i18n crispy_forms_tags static %}
{% crispy form %}

beyondtheadmin/clients/templates/clients/list.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "All clients" %}{% endblock %}

{% block css %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css"
        href="https://cdn.datatables.net/v/bs4/jszip-2.5.0/dt-1.10.23/b-1.6.5/b-html5-1.6.5/r-2.2.7/sc-2.0.3/sb-1.0.1/sp-1.2.2/sl-1.3.1/datatables.min.css"/>
{% endblock %}
{% block javascript %}
  {{ block.super }}
  <script type="text/javascript"
          src="https://cdn.datatables.net/v/bs4/jszip-2.5.0/dt-1.10.23/b-1.6.5/b-html5-1.6.5/r-2.2.7/sc-2.0.3/sb-1.0.1/sp-1.2.2/sl-1.3.1/datatables.min.js"></script>
  <script>
    $(function () {
      let table = $("#clients").DataTable({
        {% if LANGUAGE_CODE == 'fr' %}
          "language": {
            "url": "//cdn.datatables.net/plug-ins/1.10.22/i18n/French.json"
          },
        {% elif LANGUAGE_CODE == 'de' %}
          "language": {
            "url": "//cdn.datatables.net/plug-ins/1.10.22/i18n/German.json"
          },
        {% endif %}

        "columnDefs": [
          {
            "orderable": false,
            "searchable": false,
            "targets": [-1]
          },
        ],
        "lengthMenu": [10, 25, 50, 100]
      });
    });
  </script>
{% endblock %}

{% block content %}
  <header class="page-header page-header-dark bg-gradient-primary">
    <div class="container">
      <div class="page-header-content pt-4">
        <div class="row align-items-center justify-content-between">
          <div class="col-auto mt-4">
            <h1 class="page-header-title">
              {% trans "Clients" %}
            </h1>
            <div class="page-header-subtitle">
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>
  <section class="container headed-content">
    <div class="datatable card">
      <div class="card-body">
        <p>
          <a class="btn btn-success btn-large" href="{% url 'clients:create' %}">
            <i class="bi bi-person-plus-fill"></i>&nbsp; {% trans "New client" %}</a>
        </p>
        <table class="table" id="clients">
          <thead>
          <tr>
            <th class="client-name">{% trans "Name" %}</th>
            <th class="client-last-invoice-date">{% trans "Last invoice" %}</th>
            {% if has_multiple_companies %}
              <th>{% trans "Client for" %}</th>
            {% endif %}
            <th data-data="actions" class="invoice-actions d-print-none">{% trans "Actions" %}</th>
          </tr>
          </thead>
          <tbody>
          {% for client in client_list %}
            <tr>
              <td>{{ client | linebreaksbr }}</td>
              <td>{{ client.last_invoice_date|default:"n/a" }}</td>
              {% if has_multiple_companies %}
                <td>
                  <a href="{{ client.company.detail_url }}">{{ client.company }}</a>
                </td>
              {% endif %}
              <td>
                <ul class="list-unstyled">
                  <li>
                    <a href="{{ client.create_invoice_url }}" class="btn btn-sm">
                      <i class="bi bi-file-earmark-plus"></i> {% trans "New invoice" %}
                    </a>
                  </li>
                  <li><a href="{{ client.get_update_url }}" class="btn btn-sm"><i
                    class="bi bi-pencil"></i> {% trans "Edit" %}</a></li>
                  <li><a href="{{ client.get_delete_url }}" class="btn btn-sm"><i
                    class="bi bi-trash"></i> {% trans "Delete" %}</a></li>

                </ul>
              </td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </section>
{% endblock content %}

beyondtheadmin/clients/templates/clients/update.html
{% extends 'base.html' %}
{% load i18n static %}
{% block content %}
  <section class="card card-header-actions mb-4">
    <header class="card-header ">
      {% trans "Edit client" %}
    </header>
    <article class="card-body">
      <form action="{{ client.edit_url }}" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% include "clients/form.html" %}
        </form>
    </article>
  </section>

{% endblock content %}

{% block javascript %}
{{ block.super }}
  {{ form.media }}

  <script src="{% static "js/bootstrap-autocomplete.min.js" %}"></script>
  <script>
    $(document).ready(function() {
       $('#id_company_name').autoComplete({
        resolverSettings: {
          url: '{% url "api:companies-autocomplete" %}',
        },
        formatResult: function(company){
          return {id: company.uid, text: company.name + ', ' + company.city};
        },

      });

      $('#id_company_name').on('autocomplete.select', function (evt, item) {
        evt.preventDefault();
				$('#id_company_name').val(item.name);
        $('#id_address').val(item.address);
        $('#id_city').val(item.city);
        $('#id_zip_code').val(item.zip_code);
        $('#id_country').val('CH');

				});
    });
  </script>
{% endblock javascript %}